# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: 8080
  servlet:
    context-path: /risk-analyzer
management:

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: ["info", "health", "metrics", "prometheus"]

  info:
    git:
      mode: full

  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

  metrics:
    enabled:
      root: true
      jvm: true
    export:
      prometheus:
        enabled: true
        descriptions: true

logging:
  levelclaro: INFO

spring:

  application:
    name: risk-analyzer

  jackson:
    serialization.indent_output: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://ec2-52-20-66-171.compute-1.amazonaws.com:5432/d123t86j0vdr56}
    username: ${DB_USER_NAME:lbvmwnuvzstouq}
    password: ${DB_PASSWORD:ed5631d1e23ba0bfc3b153f8032a089069cbfa165af44fe751cbbb5211adba69}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: false
    properties:
      hibernate.default_schema: ${HIBERNATE_DEFAULT_SCHEMA:public}
      hibernate.generate_statistics: ${HIBERNATE_GENERATE_STATISITCS:false}
      hibernate.id.new_generator_mappings: true
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: false
      #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      #hibernate.cache.use_minimal_puts: true
      #hibernate.cache.hazelcast.use_lite_member: true
      hibernate.temp.use_jdbc_metadata_defaults: false